#!/bin/sh
if [ "$1" == "-h" -o "$1" == "--help" ]; then
	echo -e "Decode the standard input URL to standard output.\n\nUsage: $(basename $0) URL..."
else
	if [[ $# != 0 && "$*" =~ ^[^[:cntrl:]]*$ ]]; then
		for param in "$@"; do
			i="${param//+/ }"
			printf "${i//%/\\x}\n"
		done
	else
		echo "Parameter Error"
		return 1
	fi
fi
