#!/bin/sh
if [ "$1" == "-h" -o "$1" == "--help" ]; then
	echo -e "Encode the standard input STRING to standard output.\n\nUsage: $(basename $0) STRING..."
else
	if [[ $# != 0 && "$*" =~ ^[^[:cntrl:]]*$ ]]; then
		for param in "$@"; do
			printf "%s" "$param" | base64
		done
	else
		echo "Parameter Error" >&2
		return 1
	fi
fi
