#!/bin/sh
if [ "$1" == "-h" -o "$1" == "--help" ]; then
	echo -e "Batch create symlinks for specific type of files.\n\nUsage: $(basename $0) SOURCE-DIR TARGET-DIR FILE-EXT"
else
	if [ $# -ne 0 -a -d "$1" -a -r "$1" -a -d "$2" -a -w "$2" ]; then
		for i in "${1%*/}"/*.$3; do
			file="$(basename $i)"
			echo "File name: $file"
			ln -s "${1%*/}/$file" "${2%*/}/$file"
		done
	else
		echo "Parameter Error"
		return 1
	fi
fi
